### ISSUE TITLE
{Tourism Contract v1.2} -  Contracts not being displayed in Control Center

### ISSUE THREAD

**Issue by elbenxo** [jrossignol/ContractPack-Tourism#14]
Not a single tourism contract is displayed in control center, thus it is not possible to pick one up. 

I've tried several possibilities, starting a new career, loading an advanced career, etc with no sucess. 

Let me know if I can send additional information about the issue.  

Regards

**Comment by jrossignol** [comment]
They should show up once you've hit orbit (which I assume you had at least done in the advanced career).  Try cancelling a few of the offered contracts in mission control to cycle through and see if you get the tourism ones.

If none of that works, please provide a KSP.log file and I will look into this.

**Comment by elbenxo** [comment]
Issue was fixed once I've reached orbit. 

Many thanks
