### ISSUE TITLE
Add support for the lights from the Surface Mounted Lights mod

### ISSUE THREAD

**Issue by smjjames** [jrossignol/ContractPack-Tourism#19]
Could you add support for the Surface Mounted Lights mod? Because those use the 'surface light' module rather than the 'light' module and I'd like to have those count for the Space Casino. Though they should be supported for the space hotel as well.

Mod that I'm talking about: http://forum.kerbalspaceprogram.com/index.php?/topic/52760-105-surface-mounted-stock-alike-lights-for-self-illumination-v122-111515/

**Comment by jrossignol** [comment]
Fixed in Contract Configurator via https://github.com/jrossignol/ContractConfigurator/commit/2012a8d5588983f6e42fce0a8d14c9d7eaf06cb5
