### ISSUE TITLE
Investor Tour not progressing

### ISSUE THREAD

**Issue by wingot-git** [jrossignol/ContractPack-Tourism#23]
Firstly, I am running Contract Pack: Tourism Plus 1.5.1 on KSP 1.1.3.1289. I took the Investor Tour contract which says to take one of the two tourists for a tour around. Have subsequently taken a rover, picked up the tourist and completed each waypoint in order, with a message being delivered as contract completed and rewards (rep) given.

However, I then went back into mission control and find that under Tourism Plus "Investor Tour" is available again. I have then taken that mission and completed again, only for the same result again. Additionally in mission control I have 2 completed Investor Tour's sitting in the Archive.

Both times I took the "Casino" kerbal for a tour, so unaware if "Hotel" kerbal will reward properly.

Can provide further details (other mods installed, upload save, etc.) as required. Wondering if this is related to the fix for #8 ?

**Comment by wingot-git** [comment]
Also wondering if maybe it's not progressing as I'm missing a part in the tech tree currently that the mod isn't properly checking for?

**Comment by wingot-git** [comment]
Looking through https://github.com/jrossignol/ContractPack-Tourism/blob/master/GameData/ContractPacks/Tourism/CasinoBuilding.cfg I do notice that a parameter requires an Asteroid be included in the casino. I have neither the Advanced Grabbing Unit nor the upgraded Tracking Station (for unowned objects): could this be related (as I'd not be able to complete the parameters)?

**Comment by jrossignol** [comment]
The investor tour is repeatable, so that part is expected.  If you're not getting offered the casino contract, it should tell you why when you click on it (not having the right tech is a good guess though).  If you can provide a screenshot of the casino contract in mission control I can help more.

**Comment by wingot-git** [comment]
In my current game, there isn't a contract for building a casino listed at all (only taking tourists to and from one once built).

http://images.akamai.steamusercontent.com/ugc/493528961510701038/7AC6998E55ED31BA8D90CA04B60C69B865C59DC1/ is my game in its current state. I do notice there are missions for taking tourists to an asteroid or space camp, would these be silent prereqs for CasinoConstruction?

Looking into AsteroidTour I noticed that one requires level 3 tracking station. I upgraded and fast forwarded time to test this and got 2 contracts for rendezvousing with an Asteroid http://images.akamai.steamusercontent.com/ugc/493528961510698364/A756379668703AFD23F5CC6D6A6557F8A1E712C9/

Looking through the configs I can't see this being listed as a prereq for Casino/Hotel Construction but it would make a lot of sense?

I do notice in the configs the bit about RemoteTech and AntennaRange, both of which I'm not running. I also notice that this part is ONLY listed in the CasinoBuilding and HotelBuilding contracts...

**Comment by jrossignol** [comment]
This most likely means the contract failed to load. Can you send a KSP.log
file?

**Comment by wingot-git** [comment]
Just installed RemoteTech and AntennaRange and the contracts are now listed even with level 2 tracking station (http://images.akamai.steamusercontent.com/ugc/493528961510752592/7C08041BFACEDEED8F83A6CC1328CA7524223FAB/).

Appears the changes you made to support those two mods have actually made them a requirement to even display?

Confirmed: uninstalled both mods and contracts again fail to load.

Will paste KSP.log.

**Comment by wingot-git** [comment]
Can't paste the log to pastebin or pastee due to file size... Managed to get it to upload to gist (https://gist.githubusercontent.com/adrianpavone/7c3af6bb3c72b6186e30a91c4de41b05/raw/9deae15132a2bc915d0591e1446e34f0d7d34526/KSP.Log). There is some mention of RemoteTech parts I think left hanging from my install/uninstall, but the mod is definitely uninstalled and the RemoteTech directory had only a cfg file in it).

Important parts I see (everything mentioning CasinoBuilding or HotelBuilding):

```
[LOG 10:14:16.776] Config(CONTRACT_TYPE) ContractPacks/Tourism/CasinoBuilding/Tourism_Casino
[LOG 10:14:16.777] Config(@CONTRACT_TYPE[Tourism_Casino]:FOR[Tourism]:NEEDS[RemoteTech]) ContractPacks/Tourism/CasinoBuilding/@CONTRACT_TYPE[Tourism_Casino]:FOR[Tourism]:NEEDS[RemoteTech]
[LOG 10:14:16.778] Config(@CONTRACT_TYPE[Tourism_Casino]:FOR[Tourism]:NEEDS[AntennaRange&!RemoteTech]) ContractPacks/Tourism/CasinoBuilding/@CONTRACT_TYPE[Tourism_Casino]:FOR[Tourism]:NEEDS[AntennaRange&!RemoteTech]
[LOG 10:14:16.780] Config(CONTRACT_TYPE) ContractPacks/Tourism/HotelBuilding/Tourism_Hotel
[LOG 10:14:16.781] Config(@CONTRACT_TYPE[Tourism_Hotel]:FOR[Tourism]:NEEDS[RemoteTech]) ContractPacks/Tourism/HotelBuilding/@CONTRACT_TYPE[Tourism_Hotel]:FOR[Tourism]:NEEDS[RemoteTech]
[LOG 10:14:16.782] Config(@CONTRACT_TYPE[Tourism_Hotel]:FOR[Tourism]:NEEDS[AntennaRange&!RemoteTech]) ContractPacks/Tourism/HotelBuilding/@CONTRACT_TYPE[Tourism_Hotel]:FOR[Tourism]:NEEDS[AntennaRange&!RemoteTech]

[LOG 10:14:19.591] [ModuleManager] Deleting Node in file ContractPacks/Tourism/CasinoBuilding subnode: @CONTRACT_TYPE[Tourism_Casino]:FOR[Tourism]:NEEDS[AntennaRange&!RemoteTech] as it can't satisfy its NEEDS
[LOG 10:14:19.592] [ModuleManager] Deleting Node in file ContractPacks/Tourism/HotelBuilding subnode: @CONTRACT_TYPE[Tourism_Hotel]:FOR[Tourism]:NEEDS[AntennaRange&!RemoteTech] as it can't satisfy its NEEDS

[LOG 10:14:32.065] [ModuleManager] Applying node ContractPacks/Tourism/CasinoBuilding/@CONTRACT_TYPE[Tourism_Casino]:FOR[Tourism] to ContractPacks/Tourism/CasinoBuilding/Tourism_Casino
[LOG 10:14:32.068] [ModuleManager] Applying node ContractPacks/Tourism/HotelBuilding/@CONTRACT_TYPE[Tourism_Hotel]:FOR[Tourism] to ContractPacks/Tourism/HotelBuilding/Tourism_Hotel
```

**Comment by wingot-git** [comment]
The workaround, for now, seems to be the installation of RemoteTech (and run it in disabled mode) and AntennaRange (which isn't updated to 1.1.3 yet).

However, I do have a subsequent question: given the way that the casino contract & investor tour are coded, I would now have a $Tourism_CasinnoConstruction of 2. My suspicion is that would then allow me to build a second casino after I finish the first contract (as the counter is still 1)?

I know your stated reason for making the Investor Tour repeatable was to cover for if someone destroys their attraction (such as through a deorbit), but is it expected behaviour to allow people to build multiple attractions (including being able to build both casinos and hotels) by repeating the investor tour? Personally (and this is based purely on your forum posts, changelog, etc.) it seems like you should only be able to do one investor tour (as in it should be blocked if $Tourism_CasinoConstruction or $Tourism_HotelConstruction are above 0 or if an attraction is in place) and only repop if the attraction was destroyed. Subsequently, I feel like CasinoConstruction and HotelConstruction should be setting their respective counters to 0, instead of just -1 from the current value, and set that the attraction is in place until the object no longer exists (similar logic to the Space Station contract pack).

**Comment by jrossignol** [comment]
You have a RemoteTech directory - which means ModuleManager thinks you have RemoteTech installed.  Which means it applies the RemoteTech compatibility stuff, which causes the contract to fail to load because you don't _actually_ have RemoteTech.

Delete GameData/RemoteTech and you should be good.

**Comment by rottielover** [comment]
I'm having an issue with this contract where I pickup one of the two kerbals, but instead of making me do the tour it just completes the contract immediately, but then no buttons work, ie cannot revert, cannot go back to space center, cannot recover the rover, etc.   Any idea's?

**Comment by hopestoned** [comment]
Having the same Issue as rottielover. As in the tour just completes directly at Mission control without having to tour around. Except I can do everything just fine afterwards but the waypoints remain, only in the tracking station not in flight.
