### ISSUE TITLE
Tourist time-in-orbit countdown stops

### ISSUE THREAD

**Issue by docmop** [jrossignol/ContractPack-Tourism#25]
After changing the scene the countdown stops going down.

Things that did **not** help:
- moving the tourist to other parts of the vessel
- removing the pilot form the vessel
- altering orbit so it doesn't match objective anymore then reestablishing wanted orbit

Reproduction steps:
yet unknown

**Comment by jrossignol** [comment]
To be fixed in jrossignol/ContractConfigurator#595
