### ISSUE TITLE
Asteroid contract failing

### ISSUE THREAD

**Issue by nalbeza** [jrossignol/ContractPack-Tourism#31]
Hello,

Any asteroid contract i pick up is failing instantly when entering launchpad, as described in https://github.com/jrossignol/ContractConfigurator/issues/409.

Versions:
  - Contract Configurator: 1.23.1
  - Tourism Plus: 1.5.2

Thanks !

**Comment by jrossignol** [comment]
This will be fixed in Contract Configurator 1.23.2 (due out in a week or less).  Closing this issue for now, but if you still have issues after the new CC release, please feel free to re-open.
